In [2]:
list = [x*x for x in range(1,10)]

In [3]:
print (list)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [4]:
alist = [1,2,3,4,5,6,7,8,9]
emplist = []

In [5]:
v1 = [1,2,3]

In [6]:
type(v1)

list

In [13]:
v2=np.array(v1)
type(v2)
v2

array([1, 2, 3])

### Numpy

In [11]:
import numpy as np

In [14]:
array_to_square = np.arange(100000)

In [15]:
%timeit array_to_square ** 2

73.2 µs ± 430 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [16]:
l1 = ([1,2],[4,5])
l2 = ([3,4],[1,2])
l3 = l1 + l2
l3

([1, 2], [4, 5], [3, 4], [1, 2])

In [17]:
l1 = np.array(l1)
l2 = np.array(l2)
l3 = l1 + l2
type(l3)
l3
l3.ndim

2

In [18]:
d2 = np.array([[1,2,3,4],[5,6,7,8],[1,6,9,2]])

In [19]:
d2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 6, 9, 2]])

In [20]:
d2.ndim

2

### reshape

In [21]:
d2array = np.arange(100).reshape(10,10)

In [22]:
d2array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### Reshape to Vector

In [23]:
vector = d2array.reshape(100,)

In [24]:
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [25]:
d4=np.arange(100).reshape(2,5,10)

In [26]:
d4

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [27]:
k1 = np.arange(25).reshape(5,5)
k2 = np.arange(25,50).reshape(5,5)

In [28]:
k1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
k2

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [30]:
k1.shape

(5, 5)

In [31]:
k2.shape

(5, 5)

In [32]:
k1*k2 #element wise multiplication

array([[   0,   26,   54,   84,  116],
       [ 150,  186,  224,  264,  306],
       [ 350,  396,  444,  494,  546],
       [ 600,  656,  714,  774,  836],
       [ 900,  966, 1034, 1104, 1176]])

In [33]:
l1 = np.arange(1,17).reshape(4,4)
l1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
l2 = np.arange(1,21).reshape(5,4)
l2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [35]:
l2@l1

array([[ 90, 100, 110, 120],
       [202, 228, 254, 280],
       [314, 356, 398, 440],
       [426, 484, 542, 600],
       [538, 612, 686, 760]])