In [2]:
import numpy as np

In [122]:
def squares(values):
    result = []
    for v in values:
        result.append(v * v)
    return result

In [123]:
to_square = range(100000)

In [124]:
%timeit squares(to_square)

11.2 ms ± 527 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [120]:
array_to_square = np.arange(0, 100000)

In [126]:
%timeit array_to_square ** 2

37.6 µs ± 199 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [34]:
a1 = np.array([1, 2, 3, 4, 5])

In [35]:
a1

array([1, 2, 3, 4, 5])

In [36]:
a1+a1+a1

array([ 3,  6,  9, 12, 15])

In [37]:
np.arange(1,10,2).ndim

1

In [38]:
dim_0 = np.array(5)

In [33]:
dim_0.ndim

0

In [39]:
dim_2 = np.array([[1,2,3,4],[5,6,7,8]])

In [40]:
dim_2.ndim

2

In [45]:
dim_3= np.array([[[1,2,3],[4,5,6],[7,9,8]]])

In [46]:
a = np.array([[[[[[[[[[[[[5]]]]]]]]]]]]])

In [47]:
a.ndim

13

In [48]:
np.size(a)

1

In [49]:
# any float in the sequences makes
# it an array of floats
a2 = np.array([1, 2, 3, 4.0, 5.0])
a2

array([1., 2., 3., 4., 5.])

In [50]:
a3 = np.array([0]*10)
a3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
[4]*5

[4, 4, 4, 4, 4]

In [52]:
# convert a python range to numpy array
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [78]:
z= np.ones(120).reshape(10,12)
print(z*5)


[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


In [75]:
np.size(z,1)

12

In [67]:
#The np.linspace() function is similar to np.arange() , but generates an array of a
#specific number of items between the specified start and stop values:

# evenly spaced #'s between two intervals
np.linspace(1, 50, 10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [79]:
d2 = np.array([[1,2,3,4,5,6,7,8,9,0],[11,22,33,44,55,66,77,88,99,00]])

In [81]:
d2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9,  0],
       [11, 22, 33, 44, 55, 66, 77, 88, 99,  0]])

In [82]:
d2[1,4]

55

In [111]:
w = np.random.randn(12).reshape(4,3)

In [115]:
w

array([[-2.23349832, -0.65478858,  0.73256524],
       [ 1.33912694,  1.40419405,  0.54720011],
       [ 0.14383491, -0.19128825,  0.11131575],
       [-1.38740612, -1.85573316, -1.7164888 ]])

In [114]:
w[1:2, 2:]

array([[0.54720011]])

In [116]:
w[1,2]

0.5472001079323153

In [7]:
z=np.ones(120).reshape(10,12)
z.dtype

dtype('float64')

In [9]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [15]:
a = np.arange(10).reshape(2,1,5)
a

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [14]:
np.ones_like(a)

array([[[1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1]]])

In [22]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [17]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [19]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [20]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [39]:
in_arr = np.arange(81).reshape(9,9)
in_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [40]:
in_arr[3,5]

32

In [41]:
in_arr[3][5]

32

In [44]:
in_arr[3:7,3:7]=0

In [45]:
in_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29,  0,  0,  0,  0, 34, 35],
       [36, 37, 38,  0,  0,  0,  0, 43, 44],
       [45, 46, 47,  0,  0,  0,  0, 52, 53],
       [54, 55, 56,  0,  0,  0,  0, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])