In [4]:
def foo(x=[]):
    x.append(1)
    return x
foo()
foo()

[1, 1]

In [6]:
my_string ='The brown fox'
k = [print(i) for i in my_string if i not in "aeiou"]

T
h
 
b
r
w
n
 
f
x


In [10]:
x = [i**(i+1) for i in range(3)]
print(x)

[0, 1, 8]


In [11]:
lamb = lambda x: x ** 3
print(lamb(5))

125


In [12]:
import numpy as np

In [14]:
a=np.arange(20).reshape(4,5)
b=np.arange(21,41).reshape(4,5)

In [15]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [16]:
b

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [18]:
np.concatenate((a,b),axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [20]:
np.vstack((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [26]:
names = np.array(['asad','saad','free','dad','asad','haa','haa'])
data = np.random.rand(7,4)

In [27]:
names

array(['asad', 'saad', 'free', 'dad', 'asad', 'haa', 'haa'], dtype='<U4')

In [28]:
data

array([[0.1009896 , 0.03089429, 0.02361227, 0.96643041],
       [0.45179422, 0.30839323, 0.13285657, 0.94097693],
       [0.7448645 , 0.24991409, 0.48320643, 0.98724979],
       [0.08531373, 0.62275614, 0.26210164, 0.9116247 ],
       [0.67734686, 0.36920814, 0.70895046, 0.10609931],
       [0.07970628, 0.51397262, 0.71765225, 0.13231752],
       [0.47547695, 0.41066516, 0.30894777, 0.80791908]])

In [25]:
names==['asda']

array([ True, False, False, False])

In [29]:
data[names=='asad']

array([[0.1009896 , 0.03089429, 0.02361227, 0.96643041],
       [0.67734686, 0.36920814, 0.70895046, 0.10609931]])

In [5]:
for i in range(4):
    if i%2==0:
        print(i)
        else:
        print(i+1)

0
2
2
4


In [20]:
def foo():
    i=total+1
    return i
total=0
print(foo())

1


In [21]:
def foo(i, x=[]):
    x.append(x.append(i))
    return x
for i in range(3):
    y = foo(i)
print(y)

[0, None, 1, None, 2, None]


In [22]:
def to_upper(k):
    return k.upper()
x = ['ab', 'cd']
print(list(map(to_upper, x)))

['AB', 'CD']


In [24]:
lamb = lambda x: x ** 3
print(lamb(5))

125
